[package]
name = "sps-gbm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.35", features = ["derive"] }
csv = "1.2"
dirs = "5.0"
plotters = "0.3"
rand = "0.8"
rand_distr = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
statrs = "0.16"
